import { WorkflowExecutionAlreadyStartedError } from '@temporalio/client'
import {
	type InvocationLedger,
	type RunState,
	type RunStateRpc,
} from '#worker/run-records/run-state-types.ts'
import {
	workflowProjectionReservationStatuses,
	type WorkflowProjectionReserveResult,
} from '#worker/run-records/workflow-projection.ts'
import { type KodyTemporal } from './client.ts'
import { taskQueues } from './ids.ts'
import {
	projectionRowsQuery,
	projectionUpdate,
	type ProjectionCommand,
} from './workflows/workflow-projection-registry.ts'
import { kodySearchAttributes } from './search-attributes.ts'

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`
const statusMap: Record<string, string> = {
	RUNNING: 'running',
	COMPLETED: 'complete',
	FAILED: 'errored',
	CANCELLED: 'cancelled',
	TERMINATED: 'terminated',
	TIMED_OUT: 'errored',
}

export function createRunState(input: {
	ledger: InvocationLedger
	temporal: KodyTemporal
}): RunState {
	return {
		forUser(userId) {
			if (!userId.trim() || userId.includes(':'))
				throw new Error('Run state requires a valid userId.')
			const ledger = input.ledger.forUser(userId)
			const handle = async () => {
				const client = await input.temporal.client(taskQueues.runtime)
				const workflowId = `${userId}:workflow-projections`
				try {
					await client.workflow.start('WorkflowProjectionRegistry', {
						workflowId,
						taskQueue: taskQueues.runtime,
						args: [{ userId }],
						typedSearchAttributes: [
							{ key: kodySearchAttributes.userId, value: userId },
							{ key: kodySearchAttributes.surface, value: 'workflow-registry' },
						],
					})
				} catch (error) {
					if (!(error instanceof WorkflowExecutionAlreadyStartedError))
						throw error
				}
				return client.workflow.getHandle(workflowId)
			}
			const update = async (command: ProjectionCommand) =>
				(await handle()).executeUpdate(projectionUpdate, { args: [command] })
			const rows = async () => (await handle()).query(projectionRowsQuery)
			const visibleRows = async () => {
				const projections = await rows()
				const client = await input.temporal.client(taskQueues.runtime)
				const query = `KodyUserId = ${quote(userId)} AND WorkflowType = 'PackageWorkflowRun'`
				for await (const execution of client.workflow.list({ query })) {
					// Registry ids are generated by this owner's callers. Visibility is independently owner-filtered.
					const row = projections.find((row) => row.id === execution.workflowId)
					const actual = statusMap[execution.status.name]
					if (row && actual) {
						const terminal = execution.status.name !== 'RUNNING'
						if (terminal) {
							row.status = actual
							const closedAt =
								execution.closeTime?.toISOString() ?? new Date().toISOString()
							row.updatedAt =
								closedAt > row.updatedAt ? closedAt : row.updatedAt
							row.completedAt = closedAt
							await update({ action: 'upsert', projection: row })
						} else if (
							![
								'paused',
								'waiting',
								'waitingForPause',
								'queued',
								'complete',
								'errored',
								'terminated',
								'cancelled',
							].includes(row.status ?? '')
						)
							row.status = actual
					}
				}
				return projections
			}
			const rpc: RunStateRpc = {
				...ledger,
				async upsertWorkflowProjection(projection) {
					await update({ action: 'upsert', projection })
					return { ok: true }
				},
				async getWorkflowProjection({ id }) {
					return (await visibleRows()).find((row) => row.id === id) ?? null
				},
				async findWorkflowProjectionByIdempotencyKey({
					idempotencyKey,
					bindingName,
				}) {
					return (
						(await visibleRows()).find(
							(row) =>
								row.idempotencyKey === idempotencyKey &&
								(!bindingName || row.bindingName === bindingName) &&
								row.status !== 'creating',
						) ?? null
					)
				},
				async findWorkflowProjectionByBindingIdempotencyKey({
					bindingName,
					idempotencyKey,
				}) {
					return (
						(await visibleRows()).find(
							(row) =>
								row.bindingName === bindingName &&
								row.idempotencyKey === idempotencyKey,
						) ?? null
					)
				},
				async listWorkflowProjections({ limit, cursor, status, bindingName }) {
					const selected = (await visibleRows())
						.filter(
							(row) =>
								(!status || row.status === status) &&
								(!bindingName || row.bindingName === bindingName),
						)
						.sort(
							(a, b) =>
								b.createdAt.localeCompare(a.createdAt) ||
								b.id.localeCompare(a.id),
						)
					const start = cursor
						? selected.findIndex((row) => row.id === cursor) + 1
						: 0
					const projections = selected.slice(start, start + limit)
					return {
						projections,
						nextCursor:
							start + limit < selected.length ? projections.at(-1)!.id : null,
					}
				},
				async countActiveWorkflowProjections() {
					const projections = await visibleRows()

					return {
						count: projections.filter((row) =>
							workflowProjectionReservationStatuses.includes(row.status ?? ''),
						).length,
					}
				},
				async reserveWorkflowProjectionSlot(projection) {
					await visibleRows()
					return (await update({
						action: 'reserve',
						projection,
					})) as WorkflowProjectionReserveResult
				},
				async deleteWorkflowProjectionIfCreating({ id }) {
					return (await update({ action: 'delete', id })) as {
						deleted: boolean
					}
				},
				async exportState() {
					return {
						packageInvocations: await ledger.list(),
						workflowProjections: await visibleRows(),
					}
				},
				async clear() {
					await ledger.clear()
					await update({ action: 'clear' })
				},
			}
			return rpc
		},
	}
}
