-- POC baseline: final schema and seed data from all 71 APP_DB migrations and jobs.
-- Text timestamps, JSON strings and integer flags retain their published contracts.
-- ponytail: squashed POC history; use versioned Aurora migrations before cutover.

CREATE TABLE value_buckets (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	scope TEXT NOT NULL CHECK (scope IN ('session', 'app', 'user')),
	binding_key TEXT NOT NULL,
	expires_at TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	UNIQUE(user_id, scope, binding_key)
);

CREATE TABLE mcp_user_server_instructions (
	user_id TEXT PRIMARY KEY NOT NULL,
	instructions TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE mcp_memories (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	category TEXT,
	status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deleted', 'archived')),
	subject TEXT NOT NULL,
	summary TEXT NOT NULL,
	details TEXT NOT NULL DEFAULT '',
	tags_json TEXT NOT NULL DEFAULT '[]',
	dedupe_key TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	last_accessed_at TEXT,
	deleted_at TEXT
, source_uris_json TEXT NOT NULL DEFAULT '[]');

CREATE TABLE entity_sources (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	entity_kind TEXT NOT NULL,
	entity_id TEXT NOT NULL,
	repo_id TEXT NOT NULL,
	published_commit TEXT,
	indexed_commit TEXT,
	manifest_path TEXT NOT NULL DEFAULT 'kody.json',
	source_root TEXT NOT NULL DEFAULT '/',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
, last_external_check_at TEXT, external_check_until TEXT);

CREATE TABLE saved_packages (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	kody_id TEXT NOT NULL,
	description TEXT NOT NULL,
	tags_json TEXT NOT NULL DEFAULT '[]',
	search_text TEXT,
	source_id TEXT NOT NULL,
	has_app BIGINT NOT NULL DEFAULT 0 CHECK (has_app IN (0, 1)),
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
, hidden BIGINT NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1)), is_private BIGINT NOT NULL DEFAULT 1 CHECK (is_private IN (0, 1)), locked_at TEXT);

CREATE TABLE published_bundle_artifacts (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	published_commit TEXT NOT NULL,
	artifact_kind TEXT NOT NULL,
	artifact_name TEXT,
	entry_point TEXT NOT NULL,
	kv_key TEXT NOT NULL,
	dependencies_json TEXT NOT NULL DEFAULT '[]',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE "email_inboxes" (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	package_id TEXT,
	name TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE roles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	name TEXT NOT NULL UNIQUE,
	description TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE permissions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	action TEXT NOT NULL,
	entity TEXT NOT NULL,
	access TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	UNIQUE (action, entity, access)
);

CREATE TABLE community_ratings (
	id TEXT PRIMARY KEY NOT NULL,
	listing_id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	stars BIGINT NOT NULL CHECK (stars BETWEEN 1 AND 5),
	adaptation_effort BIGINT NOT NULL CHECK (adaptation_effort BETWEEN 1 AND 5),
	note TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE community_reports (
	id TEXT PRIMARY KEY NOT NULL,
	listing_id TEXT NOT NULL,
	listing_name TEXT NOT NULL,
	listing_owner_user_id TEXT NOT NULL,
	reporter_user_id TEXT NOT NULL,
	reason TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'dismissed')),
	resolved_by_user_id TEXT,
	resolved_at TEXT,
	resolution_note TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE community_bans (
	user_id TEXT PRIMARY KEY NOT NULL,
	banned_by_user_id TEXT NOT NULL,
	reason TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE usage_rollups (
	user_id TEXT NOT NULL,
	metric TEXT NOT NULL,
	month TEXT NOT NULL,
	event_count BIGINT NOT NULL DEFAULT 0,
	error_count BIGINT NOT NULL DEFAULT 0,
	total_duration_ms BIGINT NOT NULL DEFAULT 0,
	total_cpu_ms BIGINT NOT NULL DEFAULT 0,
	total_bytes BIGINT NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (user_id, metric, month)
);

CREATE TABLE system_email_daily_counters (
	local_part TEXT NOT NULL,
	day TEXT NOT NULL,
	count BIGINT NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL, operation_token TEXT,
	PRIMARY KEY (local_part, day)
);

CREATE TABLE mcp_server_settings (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	url TEXT NOT NULL,
	enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
	updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')), logo_key TEXT, logo_content_type TEXT, logo_source TEXT
	CHECK (logo_source IN ('favicon')), favicon_source_host TEXT, usage_mode TEXT NOT NULL DEFAULT 'any'
	CHECK (usage_mode IN ('any', 'packages')), allowed_packages_json TEXT NOT NULL DEFAULT '[]', last_error TEXT,
	UNIQUE(user_id, name)
);

CREATE TABLE verifications (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	type TEXT NOT NULL,
	target TEXT NOT NULL,
	secret TEXT NOT NULL,
	algorithm TEXT NOT NULL,
	digits BIGINT NOT NULL,
	period BIGINT NOT NULL,
	char_set TEXT NOT NULL,
	expires_at BIGINT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	UNIQUE (target, type)
);

CREATE TABLE "secret_buckets" (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	scope TEXT NOT NULL CHECK (scope IN ('session', 'package', 'user')),
	binding_key TEXT NOT NULL,
	expires_at TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	UNIQUE(user_id, scope, binding_key)
);

CREATE TABLE community_activity_events (
	id TEXT PRIMARY KEY NOT NULL,
	actor_user_id TEXT NOT NULL,
	event_type TEXT NOT NULL CHECK (event_type IN ('listing_published', 'listing_updated')),
	listing_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE "community_forks" (
	id TEXT PRIMARY KEY NOT NULL,
	listing_id TEXT NOT NULL,
	forker_user_id TEXT NOT NULL,
	origin_commit TEXT NOT NULL,
	forked_package_id TEXT NOT NULL,
	forked_source_id TEXT NOT NULL,
	target_kody_id TEXT NOT NULL,
	listing_name TEXT,
	listing_kody_id TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
, adopted_at TEXT, adoption_note TEXT, actor TEXT
CHECK (actor IS NULL OR actor IN ('human', 'agent')));

CREATE TABLE package_scope_grants (
	scope_owner_user_id TEXT NOT NULL,
	grantee_user_id TEXT NOT NULL,
	created_by_user_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (scope_owner_user_id, grantee_user_id),
	CHECK (scope_owner_user_id != grantee_user_id)
);

CREATE TABLE agent_package_conversation_uses (
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	conversation_id TEXT NOT NULL,
	first_used_at TEXT NOT NULL,
	last_used_at TEXT NOT NULL,
	PRIMARY KEY (user_id, package_id, conversation_id)
);

CREATE TABLE "email_sender_identities" (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	package_id TEXT,
	email TEXT NOT NULL,
	domain TEXT,
	display_name TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL CHECK (status IN ('verified')),
	verified_at TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE mcp_agent_sessions (
	do_id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE account_write_lease_repairs (
	id TEXT PRIMARY KEY NOT NULL,
	target_user_id TEXT NOT NULL,
	lease_token TEXT NOT NULL,
	lease_holder TEXT NOT NULL,
	lease_acquired_at TEXT NOT NULL,
	repaired_by_user_id TEXT NOT NULL,
	reason TEXT NOT NULL,
	created_at TEXT NOT NULL
);

CREATE TABLE webhook_endpoints (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	webhook_name TEXT NOT NULL,
	url_secret_hash TEXT NOT NULL,
	enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL,
	rotated_at TEXT NOT NULL
, url_secret_encrypted TEXT, previous_url_secret_hash TEXT, previous_url_secret_expires_at TEXT);

CREATE TABLE stripe_webhook_events (
	event_id TEXT PRIMARY KEY NOT NULL,
	event_type TEXT NOT NULL,
	processed_at TEXT NOT NULL
);

CREATE TABLE user_oauth_apps (
	user_id TEXT NOT NULL,
	slug TEXT NOT NULL,
	provider TEXT NOT NULL,
	label TEXT,
	client_id TEXT NOT NULL,
	token_url TEXT NOT NULL,
	authorize_url TEXT,
	api_base_url TEXT,
	flow TEXT NOT NULL CHECK (flow IN ('pkce', 'confidential')),
	use_pkce BIGINT CHECK (use_pkce IN (0, 1)),
	token_exchange_style TEXT CHECK (token_exchange_style IN ('form', 'basic-json', 'basic-form')),
	scope_separator TEXT,
	extra_authorize_params_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
	updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')), logo_key TEXT, logo_content_type TEXT, logo_source TEXT
	CHECK (logo_source IN ('upload', 'favicon')), favicon_source_host TEXT, client_secret_encrypted TEXT,
	PRIMARY KEY (user_id, slug)
);

CREATE TABLE email_sender_rules (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	kind TEXT NOT NULL CHECK (kind IN ('address', 'domain')),
	value TEXT NOT NULL,
	effect TEXT NOT NULL CHECK (effect IN ('allow', 'block', 'quarantine')),
	note TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE package_codemod_runs (
	id TEXT PRIMARY KEY NOT NULL,
	codemod_id TEXT NOT NULL,
	mode TEXT NOT NULL,
	scope_user_id TEXT,
	initiated_by_user_id TEXT NOT NULL,
	filters_json TEXT NOT NULL DEFAULT '{}',
	status TEXT NOT NULL,
	revert_of_run_id TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE package_codemod_run_items (
	id TEXT PRIMARY KEY NOT NULL,
	run_id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	kody_id TEXT NOT NULL,
	status TEXT NOT NULL,
	before_commit TEXT,
	after_commit TEXT,
	changed_paths_json TEXT NOT NULL DEFAULT '[]',
	findings_json TEXT NOT NULL DEFAULT '[]',
	check_summary_json TEXT,
	error TEXT,
	revert_snapshot_key TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE feature_flag_exposure_rollups (
	flag_key TEXT NOT NULL,
	user_id TEXT NOT NULL,
	day TEXT NOT NULL,
	enabled BIGINT NOT NULL CHECK (enabled IN (0, 1)),
	source TEXT NOT NULL,
	exposure_count BIGINT NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (flag_key, user_id, day, enabled, source)
);

CREATE TABLE system_email_graph_authority (
	singleton BIGINT PRIMARY KEY CHECK (singleton = 1),
	authority TEXT NOT NULL CHECK (authority = 'dedicated'),
	cutover_at TEXT NOT NULL,
	graph_mismatch_count BIGINT NOT NULL CHECK (graph_mismatch_count = 0),
	provider_link_count BIGINT NOT NULL CHECK (provider_link_count = 0)
);

CREATE TABLE "email_outbound_provider_index" (
	provider TEXT NOT NULL,
	provider_message_id TEXT NOT NULL,
	user_id TEXT NOT NULL CHECK (user_id <> 'system:email'),
	message_id TEXT NOT NULL,
	inbox_id TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (provider, provider_message_id)
);

CREATE TABLE email_inbound_due_owners (
	user_id TEXT PRIMARY KEY NOT NULL CHECK (user_id != 'system:email'),
	due_at TEXT NOT NULL,
	reason TEXT NOT NULL,
	attempt_count BIGINT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
	last_error TEXT,
	updated_at TEXT NOT NULL
);

CREATE TABLE email_outbound_provider_index_repair_owners (
	user_id TEXT PRIMARY KEY NOT NULL CHECK (user_id != 'system:email'),
	pending_count BIGINT NOT NULL CHECK (pending_count > 0),
	oldest_pending_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE email_delivery_alert_events (
	provider_event_id TEXT PRIMARY KEY NOT NULL,
	provider TEXT NOT NULL,
	event_type TEXT NOT NULL CHECK (event_type IN ('bounced', 'complained')),
	occurred_at TEXT NOT NULL,
	owner_hash TEXT,
	created_at TEXT NOT NULL
);

CREATE TABLE "email_user_graph_authority" (
	singleton BIGINT PRIMARY KEY NOT NULL CHECK (singleton = 1),
	owner_count BIGINT NOT NULL CHECK (owner_count >= 0),
	frozen_at TEXT NOT NULL,
	dropped_at TEXT NOT NULL
);

CREATE TABLE user_repos (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
, is_private BIGINT NOT NULL DEFAULT 1 CHECK (is_private IN (0, 1)));

CREATE TABLE entity_source_artifacts_push_subscriptions (
	source_id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	repo_id TEXT NOT NULL,
	subscription_id TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE d1_storage_reconcile_cursor (
	singleton BIGINT PRIMARY KEY NOT NULL CHECK (singleton = 1),
	position TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE "users" (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	username TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	email_verified_at TEXT,
	plan TEXT NOT NULL DEFAULT 'free' CHECK (
		plan IN ('free', 'standard', 'pro', 'max')
	),
	stable_user_id TEXT NOT NULL,
	stripe_customer_id TEXT,
	stripe_plan TEXT,
	stripe_plan_refreshed_at TEXT,
	display_name TEXT,
	bio TEXT,
	profile_visibility TEXT NOT NULL DEFAULT 'public' CHECK (
		profile_visibility IN ('public', 'private')
	),
	avatar_key TEXT,
	account_type TEXT NOT NULL DEFAULT 'person' CHECK (
		account_type IN ('person', 'platform')
	),
	deleting_at TEXT,
	active_write_count BIGINT NOT NULL DEFAULT 0,
	active_write_expires_at TEXT,
	suspended_at TEXT,
	email_outbound_paused_at TEXT,
	password_changed_at TEXT,
	job_retention_success_once_days BIGINT CHECK (
		job_retention_success_once_days IS NULL
		OR (
			job_retention_success_once_days >= 1
			AND job_retention_success_once_days <= 365
		)
	),
	job_retention_failed_once_days BIGINT CHECK (
		job_retention_failed_once_days IS NULL
		OR (
			job_retention_failed_once_days >= 1
			AND job_retention_failed_once_days <= 365
		)
	),
	job_retention_disabled_recurring_days BIGINT CHECK (
		job_retention_disabled_recurring_days IS NULL
		OR (
			job_retention_disabled_recurring_days >= 1
			AND job_retention_disabled_recurring_days <= 365
		)
	)
, onboarding_checklist_dismissed_at TEXT, email_verification_delivery_status TEXT, email_verification_delivery_at TEXT, email_verification_delivery_detail TEXT, email_verification_delivery_class TEXT, utm_source TEXT, utm_medium TEXT, utm_campaign TEXT, utm_content TEXT, utm_term TEXT, first_touch_landing_path TEXT, first_touch_referrer TEXT, first_mcp_connected_at TEXT, first_execute_at TEXT, first_saved_package_at TEXT, mcp_client_name TEXT, last_active_at TEXT, first_search_at TEXT, entitlement_ladder TEXT NOT NULL DEFAULT 'public'
	CHECK (entitlement_ladder IN ('public', 'legacy')), stripe_price_id TEXT, second_agent_standard_gift_granted_at TEXT, second_agent_standard_gift_expires_at TEXT, referral_standard_credit_expires_at TEXT, experiments_opt_in BIGINT NOT NULL DEFAULT 0
	CHECK (experiments_opt_in IN (0, 1)), first_secret_at TEXT, first_integration_at TEXT, first_job_at TEXT, stripe_credits_eligible BIGINT NOT NULL DEFAULT 0
	CHECK (stripe_credits_eligible IN (0, 1)), admin_credits_eligible BIGINT NOT NULL DEFAULT 0
	CHECK (admin_credits_eligible IN (0, 1)));

CREATE TABLE platform_oauth_apps (
	-- SQLite quirk: plain TEXT PRIMARY KEY still allows NULL; be explicit.
	slug TEXT PRIMARY KEY NOT NULL,
	provider TEXT NOT NULL,
	label TEXT,
	client_id TEXT NOT NULL,
	client_secret_encrypted TEXT,
	token_url TEXT NOT NULL,
	authorize_url TEXT NOT NULL,
	api_base_url TEXT,
	flow TEXT NOT NULL CHECK (flow IN ('pkce', 'confidential')),
	use_pkce BIGINT CHECK (use_pkce IN (0, 1)),
	token_exchange_style TEXT CHECK (token_exchange_style IN ('form', 'basic-json', 'basic-form')),
	scope_separator TEXT,
	extra_authorize_params_json TEXT NOT NULL DEFAULT '{}',
	-- Scope menu: the verified superset an operator may ever request...
	allowed_scopes_json TEXT NOT NULL DEFAULT '[]',
	-- ...and the minimal set the connect flow requests by default.
	default_scopes_json TEXT NOT NULL DEFAULT '[]',
	required_hosts_json TEXT NOT NULL DEFAULT '[]',
	enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
	updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
, logo_key TEXT, logo_content_type TEXT, description TEXT);

CREATE TABLE saved_package_search_index_debt (
	package_id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	generation BIGINT NOT NULL DEFAULT 0,
	embed_text TEXT NOT NULL,
	last_error TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE username_redirects (
	-- SQLite quirk: plain TEXT PRIMARY KEY still allows NULL; be explicit.
	old_username TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);

CREATE TABLE package_kody_id_redirects (
	user_id TEXT NOT NULL,
	old_kody_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
	PRIMARY KEY (user_id, old_kody_id)
);

CREATE TABLE repo_session_due_owners (
	user_id TEXT PRIMARY KEY NOT NULL,
	due_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE repo_session_storage_bucket_cursor (
	singleton BIGINT PRIMARY KEY CHECK (singleton = 1),
	position TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL
);

CREATE TABLE "user_storage_buckets" (
	user_id TEXT NOT NULL,
	storage_id TEXT NOT NULL,
	kind TEXT NOT NULL CHECK (
		kind IN ('job', 'package', 'execute', 'repo_session', 'unknown')
	),
	created_at TEXT NOT NULL,
	last_seen_at TEXT NOT NULL,
	estimated_bytes BIGINT,
	estimated_bytes_updated_at TEXT,
	PRIMARY KEY (user_id, storage_id)
);

CREATE TABLE "package_invocation_tokens" (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	name TEXT NOT NULL,
	token_hash TEXT NOT NULL,
	export_names_json TEXT NOT NULL DEFAULT '[]',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	last_used_at TEXT,
	revoked_at TEXT
);

CREATE TABLE vector_embed_fingerprints (
	user_id TEXT NOT NULL,
	vector_id TEXT NOT NULL,
	content_hash TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (user_id, vector_id)
);

CREATE TABLE "platform_feedback" (
	id TEXT PRIMARY KEY NOT NULL,
	submitter_user_id TEXT NOT NULL,
	category TEXT NOT NULL CHECK (
		category IN (
			'friction',
			'bug',
			'experience',
			'suggestion',
			'cancellation',
			'other'
		)
	),
	summary TEXT NOT NULL CHECK (
		length(summary) BETWEEN 1 AND 200
	),
	details TEXT NOT NULL CHECK (
		length(details) BETWEEN 1 AND 8000
	),
	status TEXT NOT NULL DEFAULT 'open' CHECK (
		status IN ('open', 'triaged', 'resolved', 'dismissed')
	),
	reviewed_by_user_id TEXT,
	reviewed_at TEXT,
	admin_note TEXT CHECK (
		admin_note IS NULL OR length(admin_note) <= 2000
	),
	revision BIGINT NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	submitter_username TEXT NOT NULL,
	submitter_email TEXT NOT NULL
);

CREATE TABLE platform_provider_marks (
	slug TEXT PRIMARY KEY,
	label TEXT NOT NULL,
	aliases_json TEXT NOT NULL DEFAULT '[]',
	logo_key TEXT,
	logo_content_type TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE "community_listings" (
	id TEXT PRIMARY KEY NOT NULL,
	owner_user_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	kody_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	tags_json TEXT NOT NULL DEFAULT '[]',
	category TEXT NOT NULL DEFAULT 'other' CHECK (
		category IN (
			'integrations',
			'examples',
			'productivity',
			'apps',
			'utilities',
			'other'
		)
	),
	search_text TEXT,
	readme_content TEXT,
	license TEXT NOT NULL,
	package_version TEXT,
	pinned_commit TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'delisted')),
	featured_at TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	published_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE referrals (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	referrer_stable_user_id TEXT NOT NULL,
	referee_stable_user_id TEXT NOT NULL,
	created_at TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'pending'
		CHECK (status IN ('pending', 'rewarded', 'rejected')),
	rewarded_at TEXT,
	reward_invoice_id TEXT,
	reject_reason TEXT,
	held_invoice_id TEXT,
	held_period_end_at TEXT,
	credits_granted_at TEXT
);

CREATE TABLE user_tips_email_opt_outs (
	user_id TEXT PRIMARY KEY NOT NULL,
	opted_out_at TEXT NOT NULL
);

CREATE TABLE user_usage_campaigns (
	user_id TEXT PRIMARY KEY NOT NULL,
	state TEXT NOT NULL,
	entered_at TEXT NOT NULL,
	send_count BIGINT NOT NULL DEFAULT 0,
	last_sent_at TEXT,
	last_evaluated_at TEXT NOT NULL,
	origin TEXT NOT NULL CHECK (origin IN ('seed', 'event')),
	cooling_terminal BIGINT NOT NULL DEFAULT 0 CHECK (cooling_terminal IN (0, 1)),
	ever_activated BIGINT NOT NULL DEFAULT 0,
	first_activated_at TEXT,
	advocate_sent_at TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE user_usage_campaign_sends (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id TEXT NOT NULL,
	state TEXT NOT NULL,
	template TEXT NOT NULL,
	send_index BIGINT NOT NULL,
	sent_at TEXT NOT NULL,
	UNIQUE (user_id, state, send_index)
);

CREATE TABLE package_share_grants (
	id TEXT PRIMARY KEY NOT NULL,
	package_id TEXT NOT NULL,
	owner_user_id TEXT NOT NULL,
	invitee_email TEXT,
	invitee_username TEXT,
	grantee_user_id TEXT,
	status TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'revoked', 'left')),
	role TEXT NOT NULL DEFAULT 'use' CHECK (role IN ('use')),
	trust_level TEXT CHECK (trust_level IN ('follow', 'pin') OR trust_level IS NULL),
	accepted_published_commit TEXT,
	invited_at TEXT NOT NULL,
	accepted_at TEXT,
	revoked_at TEXT,
	left_at TEXT,
	last_acknowledged_at TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	CHECK (invitee_email IS NOT NULL OR grantee_user_id IS NOT NULL)
);

CREATE TABLE durable_object_duration_daily (
	user_id TEXT NOT NULL,
	do_class TEXT NOT NULL,
	day TEXT NOT NULL,
	active_ms BIGINT NOT NULL,
	object_count BIGINT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (user_id, do_class, day)
);

CREATE TABLE durable_object_duration_coverage_daily (
	day TEXT PRIMARY KEY,
	total_active_ms BIGINT NOT NULL,
	attributed_active_ms BIGINT NOT NULL,
	object_count BIGINT NOT NULL,
	attributed_object_count BIGINT NOT NULL,
	truncated BIGINT NOT NULL DEFAULT 0,
	updated_at TEXT NOT NULL
);

CREATE TABLE credit_wallets (
	user_id TEXT PRIMARY KEY NOT NULL,
	balance_micro_usd BIGINT NOT NULL DEFAULT 0,
	auto_refill_enabled BIGINT NOT NULL DEFAULT 0
		CHECK (auto_refill_enabled IN (0, 1)),
	auto_refill_threshold_cents BIGINT,
	auto_refill_amount_cents BIGINT,
	auto_refill_monthly_cap_cents BIGINT,
	auto_refill_payment_method_id TEXT,
	auto_refill_failed_at TEXT,
	notify_auto_refilled BIGINT NOT NULL DEFAULT 1
		CHECK (notify_auto_refilled IN (0, 1)),
	notify_monthly_cap BIGINT NOT NULL DEFAULT 1
		CHECK (notify_monthly_cap IN (0, 1)),
	notify_low_balance BIGINT NOT NULL DEFAULT 1
		CHECK (notify_low_balance IN (0, 1)),
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE credit_ledger_entries (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	kind TEXT NOT NULL
		CHECK (kind IN ('top_up', 'auto_refill', 'admin_grant', 'debit')),
	amount_micro_usd BIGINT NOT NULL,
	meter TEXT,
	month TEXT,
	units BIGINT,
	stripe_reference TEXT,
	granted_by_user_id TEXT,
	note TEXT,
	created_at TEXT NOT NULL
);

CREATE TABLE credit_debit_progress (
	user_id TEXT NOT NULL,
	month TEXT NOT NULL,
	meter TEXT NOT NULL,
	accounted_units BIGINT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (user_id, month, meter)
);

CREATE TABLE credit_debit_cursor (
	singleton BIGINT PRIMARY KEY NOT NULL CHECK (singleton = 1),
	position TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE jobs (
	id TEXT PRIMARY KEY NOT NULL,
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	source_id TEXT NOT NULL,
	published_commit TEXT,
	repo_check_policy_json TEXT,
	storage_id TEXT NOT NULL,
	params_json TEXT,
	schedule_json TEXT NOT NULL,
	timezone TEXT NOT NULL,
	enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	kill_switch_enabled BIGINT NOT NULL DEFAULT 0 CHECK (kill_switch_enabled IN (0, 1)),
	caller_context_json TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	last_run_at TEXT,
	last_run_status TEXT,
	next_run_at TEXT NOT NULL,
	preserved BIGINT NOT NULL DEFAULT 0 CHECK (preserved IN (0, 1)),
	claim_token TEXT,
	running_since TEXT,
	lease_expires_at TEXT,
	claimed_scheduled_for TEXT,
	retry_scheduled_for TEXT,
	retry_count BIGINT NOT NULL DEFAULT 0,
	last_completed_scheduled_for TEXT,
	expires_at TEXT
);

CREATE TABLE archived_job_artifacts (
	id TEXT PRIMARY KEY,
	job_id TEXT NOT NULL UNIQUE,
	user_id TEXT NOT NULL,
	source_id TEXT NOT NULL,
	published_commit TEXT NOT NULL,
	storage_id TEXT NOT NULL,
	retain_until TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL
);

CREATE TABLE password_resets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at BIGINT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE value_entries (
	bucket_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	value TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (bucket_id, name),
	FOREIGN KEY (bucket_id) REFERENCES value_buckets(id) ON DELETE CASCADE
);

CREATE TABLE mcp_memory_conversation_suppressions (
	user_id TEXT NOT NULL,
	conversation_id TEXT NOT NULL,
	memory_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	last_seen_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	expires_at TEXT NOT NULL,
	PRIMARY KEY (user_id, conversation_id, memory_id),
	FOREIGN KEY (memory_id) REFERENCES mcp_memories(id) ON DELETE CASCADE
);

CREATE TABLE "email_inbox_addresses" (
	id TEXT PRIMARY KEY,
	inbox_id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	address TEXT NOT NULL,
	local_part TEXT NOT NULL,
	domain TEXT NOT NULL,
	enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	FOREIGN KEY (inbox_id) REFERENCES "email_inboxes"(id) ON DELETE CASCADE
);

CREATE TABLE role_permissions (
	role_id BIGINT NOT NULL,
	permission_id BIGINT NOT NULL,
	PRIMARY KEY (role_id, permission_id),
	FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
	FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE user_roles (
	user_id BIGINT NOT NULL,
	role_id BIGINT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (user_id, role_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE email_verifications (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at BIGINT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE pending_email_changes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	new_email TEXT NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at BIGINT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE passkeys (
	id TEXT PRIMARY KEY NOT NULL,
	aaguid TEXT NOT NULL,
	public_key TEXT NOT NULL,
	user_id BIGINT NOT NULL,
	webauthn_user_handle TEXT NOT NULL,
	counter BIGINT NOT NULL DEFAULT 0,
	device_type TEXT NOT NULL,
	backed_up BIGINT NOT NULL DEFAULT 0,
	transports TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), name TEXT NOT NULL DEFAULT '', last_used_at TEXT,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE oauth_connections (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	provider_name TEXT NOT NULL,
	provider_id TEXT NOT NULL,
	user_id BIGINT NOT NULL,
	provider_display_name TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	UNIQUE (provider_name, provider_id),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE feature_flags (
	key TEXT PRIMARY KEY NOT NULL,
	enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
	rollout_percent BIGINT CHECK (rollout_percent BETWEEN 0 AND 100),
	note TEXT NOT NULL DEFAULT '',
	updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
, audience TEXT NOT NULL DEFAULT 'everyone'
	CHECK (audience IN ('everyone', 'experiments_opt_in')));

CREATE TABLE feature_flag_user_overrides (
	flag_key TEXT NOT NULL,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	enabled BIGINT NOT NULL CHECK (enabled IN (0, 1)),
	updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (flag_key, user_id)
);

CREATE TABLE system_email_threads (
	id TEXT PRIMARY KEY,
	inbox_id TEXT,
	subject_normalized TEXT NOT NULL DEFAULT '',
	root_message_id_header TEXT,
	last_message_at TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id) ON DELETE SET NULL
);

CREATE TABLE "user_integrations" (
	user_id TEXT NOT NULL,
	name TEXT NOT NULL,
	app_slug TEXT,
	platform_app_slug TEXT REFERENCES platform_oauth_apps(slug) ON DELETE RESTRICT,
	account_label TEXT,
	description TEXT NOT NULL DEFAULT '',
	scopes_json TEXT NOT NULL DEFAULT '[]',
	required_hosts_json TEXT NOT NULL DEFAULT '[]',
	connected_at TEXT,
	token_refreshed_at TEXT,
	created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
	updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')), access_token_encrypted TEXT, refresh_token_encrypted TEXT, usage_mode TEXT NOT NULL DEFAULT 'any'
	CHECK (usage_mode IN ('any', 'packages')), allowed_packages_json TEXT NOT NULL DEFAULT '[]', auth_failed_at TEXT, auth_failed_reason TEXT, auth_failed_provider_error TEXT, auth_failed_provider_description TEXT, auth_failed_http_status BIGINT, auth_failed_reconnectable BIGINT
	CHECK (auth_failed_reconnectable IN (0, 1)),
	PRIMARY KEY (user_id, name),
	FOREIGN KEY (user_id, app_slug) REFERENCES user_oauth_apps(user_id, slug) ON DELETE RESTRICT,
	CHECK ((app_slug IS NULL) <> (platform_app_slug IS NULL))
);

CREATE TABLE user_mcp_oauth_clients (
	id TEXT PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	client_id TEXT NOT NULL,
	label TEXT NOT NULL,
	redirect_uris_json TEXT NOT NULL,
	created_at TEXT NOT NULL,
	revoked_at TEXT,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE transactional_email_delivery_index (
	provider_message_id TEXT PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	kind TEXT NOT NULL,
	recipient TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE "secret_entries" (
	bucket_id TEXT NOT NULL,
	name TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	encrypted_value TEXT NOT NULL,
	allowed_hosts TEXT NOT NULL DEFAULT '[]',
	lookup_hash TEXT,
	allowed_packages TEXT NOT NULL DEFAULT '[]',
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	expires_at TEXT,
	PRIMARY KEY (bucket_id, name),
	FOREIGN KEY (bucket_id) REFERENCES secret_buckets (id) ON DELETE CASCADE
);

CREATE TABLE user_email_claims (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	email TEXT NOT NULL,
	status TEXT NOT NULL CHECK (status IN ('claimed', 'released')),
	claimed_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	released_at TEXT,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	UNIQUE (user_id, email)
);

CREATE TABLE pending_email_claim_releases (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	email TEXT NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at BIGINT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE site_banners (
	id TEXT PRIMARY KEY NOT NULL,
	enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
	priority BIGINT NOT NULL DEFAULT 0 CHECK (priority BETWEEN 0 AND 1000),
	title TEXT NOT NULL,
	body TEXT NOT NULL DEFAULT '',
	cta_href TEXT,
	cta_label TEXT,
	secondary_href TEXT,
	secondary_label TEXT,
	severity TEXT NOT NULL DEFAULT 'info' CHECK (
		severity IN ('info', 'warning', 'success', 'promo')
	),
	look TEXT NOT NULL DEFAULT 'strip' CHECK (look IN ('strip', 'promo', 'card')),
	icon TEXT,
	image_url TEXT,
	page_targeting TEXT NOT NULL DEFAULT 'all' CHECK (
		page_targeting IN ('all', 'routes')
	),
	route_patterns TEXT NOT NULL DEFAULT '[]',
	audience TEXT NOT NULL DEFAULT 'everyone' CHECK (
		audience IN ('everyone', 'logged_out', 'logged_in', 'users', 'plans')
	),
	audience_user_ids TEXT NOT NULL DEFAULT '[]',
	audience_plans TEXT NOT NULL DEFAULT '[]',
	dismissible BIGINT NOT NULL DEFAULT 1 CHECK (dismissible IN (0, 1)),
	starts_at TEXT,
	ends_at TEXT,
	created_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
	updated_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE email_notification_destinations (
	id TEXT PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	email TEXT NOT NULL,
	verified_at TEXT,
	is_default BIGINT NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE secret_provider_bindings (
	user_id TEXT NOT NULL,
	provider_id TEXT NOT NULL,
	package_id TEXT NOT NULL,
	door_secret_name TEXT NOT NULL,
	config_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	updated_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (user_id, provider_id),
	FOREIGN KEY (package_id) REFERENCES saved_packages(id) ON DELETE CASCADE
);

CREATE TABLE webhook_apply_destination_pending (
	user_id TEXT NOT NULL,
	webhook_endpoint_id TEXT NOT NULL,
	destination_fingerprint TEXT NOT NULL,
	destination_json TEXT NOT NULL,
	package_id TEXT NOT NULL,
	webhook_name TEXT NOT NULL,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (user_id, webhook_endpoint_id, destination_fingerprint),
	FOREIGN KEY (webhook_endpoint_id) REFERENCES webhook_endpoints(id) ON DELETE CASCADE
);

CREATE TABLE webhook_apply_destination_grants (
	user_id TEXT NOT NULL,
	webhook_endpoint_id TEXT NOT NULL,
	destination_fingerprint TEXT NOT NULL,
	destination_json TEXT NOT NULL,
	package_id TEXT NOT NULL,
	webhook_name TEXT NOT NULL,
	approved_at TEXT NOT NULL,
	PRIMARY KEY (user_id, webhook_endpoint_id, destination_fingerprint),
	FOREIGN KEY (webhook_endpoint_id) REFERENCES webhook_endpoints(id) ON DELETE CASCADE
);

CREATE TABLE system_email_messages (
	id TEXT PRIMARY KEY,
	direction TEXT NOT NULL CHECK (direction IN ('inbound', 'outbound')),
	inbox_id TEXT,
	thread_id TEXT,
	sender_identity_id TEXT,
	from_address TEXT NOT NULL,
	envelope_from TEXT,
	to_addresses_json TEXT NOT NULL DEFAULT '[]',
	cc_addresses_json TEXT NOT NULL DEFAULT '[]',
	bcc_addresses_json TEXT NOT NULL DEFAULT '[]',
	reply_to_addresses_json TEXT NOT NULL DEFAULT '[]',
	subject TEXT NOT NULL DEFAULT '',
	message_id_header TEXT,
	in_reply_to_header TEXT,
	references_json TEXT NOT NULL DEFAULT '[]',
	headers_json TEXT NOT NULL DEFAULT '{}',
	auth_results TEXT,
	text_body TEXT,
	html_body TEXT,
	raw_size BIGINT NOT NULL DEFAULT 0,
	processing_status TEXT NOT NULL CHECK (
		processing_status IN ('stored', 'sent', 'failed')
	),
	provider_message_id TEXT,
	error TEXT,
	received_at TEXT,
	sent_at TEXT,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	raw_mime_key TEXT,
	delivery_status TEXT CHECK (
		delivery_status IS NULL
		OR delivery_status IN (
			'delivered', 'deferred', 'bounced', 'failed', 'rejected', 'complained'
		)
	),
	delivery_status_at TEXT,
	classification TEXT NOT NULL DEFAULT 'accepted'
		CHECK (classification IN ('accepted', 'quarantined')),
	classification_reason TEXT,
	FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id) ON DELETE SET NULL,
	FOREIGN KEY (thread_id) REFERENCES system_email_threads(id) ON DELETE SET NULL,
	FOREIGN KEY (sender_identity_id) REFERENCES email_sender_identities(id)
		ON DELETE SET NULL
);

CREATE TABLE site_banner_dismissals (
	banner_id TEXT NOT NULL REFERENCES site_banners (id) ON DELETE CASCADE,
	user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	dismissed_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (banner_id, user_id)
);

CREATE TABLE pending_email_destination_verifications (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	user_id BIGINT NOT NULL,
	destination_id TEXT NOT NULL,
	token_hash TEXT NOT NULL UNIQUE,
	expires_at BIGINT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (destination_id) REFERENCES email_notification_destinations(id)
		ON DELETE CASCADE
);

CREATE TABLE secret_provider_grants (
	user_id TEXT NOT NULL,
	provider_id TEXT NOT NULL,
	canonical_ref TEXT NOT NULL,
	package_id TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
	PRIMARY KEY (user_id, provider_id, canonical_ref, package_id),
	FOREIGN KEY (package_id) REFERENCES saved_packages(id) ON DELETE CASCADE,
	FOREIGN KEY (user_id, provider_id)
		REFERENCES secret_provider_bindings(user_id, provider_id)
		ON DELETE CASCADE
);

CREATE TABLE system_email_attachments (
	id TEXT PRIMARY KEY,
	message_id TEXT NOT NULL,
	filename TEXT,
	content_type TEXT NOT NULL,
	content_id TEXT,
	disposition TEXT,
	size BIGINT NOT NULL DEFAULT 0,
	storage_kind TEXT NOT NULL CHECK (
		storage_kind IN ('raw-mime', 'external', 'unavailable')
	),
	storage_key TEXT,
	created_at TEXT NOT NULL,
	FOREIGN KEY (message_id) REFERENCES system_email_messages(id)
		ON DELETE CASCADE
);

CREATE TABLE system_email_delivery_events (
	id TEXT PRIMARY KEY,
	message_id TEXT,
	inbox_id TEXT,
	event_type TEXT NOT NULL CHECK (
		event_type IN (
			'receive_started', 'received', 'rejected', 'send_requested', 'sent',
			'failed', 'delivered', 'deferred', 'bounced', 'complained'
		)
	),
	provider TEXT NOT NULL DEFAULT 'kody',
	provider_message_id TEXT,
	provider_event_id TEXT,
	detail_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL,
	needs_effect_reconcile BIGINT NOT NULL DEFAULT 1
		CHECK (needs_effect_reconcile IN (0, 1)),
	usage_effect_recorded_at TEXT,
	usage_month TEXT,
	usage_bytes BIGINT,
	usage_duration_ms BIGINT,
	state TEXT CHECK (
		state IS NULL
		OR state IN (
			'pending', 'storing', 'cleaning', 'received', 'rejected',
			'orphan-cleaned'
		)
	),
	fingerprint TEXT,
	storage_lease TEXT,
	storage_lease_at TEXT,
	cleanup_lease TEXT,
	cleanup_lease_at TEXT,
	cleanup_retry_at TEXT,
	expected_attachment_count BIGINT,
	finalization_token TEXT,
	reconcile_after TEXT,
	dedupe_expires_at TEXT,
	usage_effect_suppressed_at TEXT,
	usage_started_at TEXT,
	usage_effect_retry_at TEXT,
	usage_effect_lease TEXT,
	usage_effect_lease_at TEXT,
	subscription_effect_state TEXT CHECK (
		subscription_effect_state IS NULL
		OR subscription_effect_state IN (
			'pending', 'processing', 'complete', 'dead-letter'
		)
	),
	subscription_effect_lease TEXT,
	subscription_effect_lease_at TEXT,
	subscription_effect_retry_at TEXT,
	subscription_effect_attempt_count BIGINT,
	subscription_effect_dead_letter_at TEXT,
	subscription_effect_last_error TEXT,
	updated_at TEXT,
	FOREIGN KEY (message_id) REFERENCES system_email_messages(id)
		ON DELETE SET NULL,
	FOREIGN KEY (inbox_id) REFERENCES email_inboxes(id) ON DELETE SET NULL
);

CREATE INDEX idx_password_resets_user_id ON password_resets(user_id);

CREATE INDEX idx_password_resets_token_hash ON password_resets(token_hash);

CREATE INDEX idx_value_buckets_user_scope_binding
	ON value_buckets(user_id, scope, binding_key);

CREATE INDEX idx_value_entries_bucket_id
	ON value_entries(bucket_id);

CREATE INDEX idx_value_entries_name
	ON value_entries(name);

CREATE INDEX idx_mcp_memories_user_status_updated
	ON mcp_memories(user_id, status, updated_at);

CREATE INDEX idx_mcp_memories_user_category_status
	ON mcp_memories(user_id, category, status);

CREATE INDEX idx_mcp_memories_user_dedupe_key
	ON mcp_memories(user_id, dedupe_key);

CREATE INDEX idx_mcp_memory_suppressions_expires_at
	ON mcp_memory_conversation_suppressions(expires_at);

CREATE UNIQUE INDEX idx_entity_sources_user_entity
ON entity_sources(user_id, entity_kind, entity_id);

CREATE UNIQUE INDEX idx_entity_sources_repo_id
ON entity_sources(repo_id);

CREATE INDEX idx_entity_sources_user_id
ON entity_sources(user_id);

CREATE UNIQUE INDEX idx_saved_packages_user_kody_id
ON saved_packages(user_id, kody_id);

CREATE UNIQUE INDEX idx_saved_packages_user_name
ON saved_packages(user_id, name);

CREATE UNIQUE INDEX idx_saved_packages_source_id
ON saved_packages(source_id);

CREATE UNIQUE INDEX idx_published_bundle_artifacts_source_identity
ON published_bundle_artifacts(
	user_id,
	source_id,
	artifact_kind,
	COALESCE(artifact_name, ''),
	entry_point
);

CREATE INDEX idx_published_bundle_artifacts_user_id
ON published_bundle_artifacts(user_id);

CREATE INDEX idx_published_bundle_artifacts_source_id
ON published_bundle_artifacts(source_id);

CREATE UNIQUE INDEX idx_email_inboxes_user_name
ON email_inboxes(user_id, name);

CREATE INDEX idx_email_inboxes_user_created_at
ON email_inboxes(user_id, created_at);

CREATE UNIQUE INDEX idx_email_inbox_addresses_address
ON email_inbox_addresses(address);

CREATE INDEX idx_email_inbox_addresses_inbox_id
ON email_inbox_addresses(inbox_id);

CREATE INDEX idx_entity_sources_external_check
	ON entity_sources(last_external_check_at);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);

CREATE UNIQUE INDEX idx_community_ratings_listing_user
ON community_ratings(listing_id, user_id);

CREATE INDEX idx_community_reports_status
ON community_reports(status);

CREATE INDEX idx_email_verifications_user_id ON email_verifications(user_id);

CREATE INDEX idx_email_verifications_token_hash ON email_verifications(token_hash);

CREATE INDEX idx_usage_rollups_user_month
ON usage_rollups(user_id, month);

CREATE INDEX idx_pending_email_changes_user_id
	ON pending_email_changes(user_id);

CREATE UNIQUE INDEX idx_pending_email_changes_new_email
	ON pending_email_changes(new_email);

CREATE INDEX idx_pending_email_changes_token_hash
	ON pending_email_changes(token_hash);

CREATE INDEX idx_mcp_server_settings_user_enabled
	ON mcp_server_settings(user_id, enabled);

CREATE INDEX idx_verifications_target_type ON verifications(target, type);

CREATE INDEX idx_passkeys_user_id ON passkeys(user_id);

CREATE INDEX idx_usage_rollups_month
ON usage_rollups(month);

CREATE INDEX idx_published_bundle_artifacts_created_at
ON published_bundle_artifacts(created_at);

CREATE INDEX idx_oauth_connections_user_id ON oauth_connections(user_id);

CREATE INDEX idx_secret_buckets_user_scope_binding
	ON secret_buckets(user_id, scope, binding_key);

CREATE INDEX idx_feature_flag_user_overrides_user_id
ON feature_flag_user_overrides(user_id);

CREATE INDEX idx_community_activity_events_actor_created
ON community_activity_events(actor_user_id, created_at);

CREATE INDEX idx_community_activity_events_listing_id
ON community_activity_events(listing_id);

CREATE INDEX idx_community_forks_listing_id
	ON community_forks(listing_id);

CREATE INDEX idx_community_forks_forker_listing
	ON community_forks(forker_user_id, listing_id);

CREATE INDEX idx_package_scope_grants_grantee_user_id
ON package_scope_grants(grantee_user_id);

CREATE INDEX idx_agent_package_conversation_uses_user_last_used
ON agent_package_conversation_uses(user_id, last_used_at);

CREATE INDEX idx_community_forks_forked_package_id
ON community_forks(forked_package_id);

CREATE UNIQUE INDEX idx_email_sender_identities_user_email
ON email_sender_identities(user_id, email);

CREATE INDEX idx_email_sender_identities_user_domain
ON email_sender_identities(user_id, domain);

CREATE INDEX idx_mcp_agent_sessions_user_id
ON mcp_agent_sessions(user_id);

CREATE UNIQUE INDEX idx_webhook_endpoints_user_package_name
ON webhook_endpoints(user_id, package_id, webhook_name);

CREATE INDEX idx_webhook_endpoints_user_created_at
ON webhook_endpoints(user_id, created_at);

CREATE INDEX idx_stripe_webhook_events_processed_at
ON stripe_webhook_events(processed_at);

CREATE INDEX idx_user_oauth_apps_user_provider
ON user_oauth_apps(user_id, provider);

CREATE UNIQUE INDEX idx_email_sender_rules_user_kind_value
	ON email_sender_rules(user_id, kind, value);

CREATE INDEX idx_package_codemod_run_items_run_id
ON package_codemod_run_items(run_id);

CREATE INDEX idx_package_codemod_runs_codemod_created
ON package_codemod_runs(codemod_id, created_at);

CREATE INDEX idx_feature_flag_exposure_rollups_user_id
	ON feature_flag_exposure_rollups (user_id);

CREATE INDEX idx_feature_flag_exposure_rollups_day
	ON feature_flag_exposure_rollups (day);

CREATE INDEX idx_entity_sources_pending_external_reconcile
ON entity_sources(external_check_until, last_external_check_at, id)
WHERE entity_kind = 'package' AND external_check_until IS NOT NULL;

CREATE INDEX idx_system_email_threads_last_message_at
ON system_email_threads(last_message_at);

CREATE INDEX idx_system_email_threads_root_message_id
ON system_email_threads(root_message_id_header);

CREATE INDEX idx_system_email_messages_created_at
ON system_email_messages(created_at);

CREATE INDEX idx_system_email_messages_inbox_created_at
ON system_email_messages(inbox_id, created_at);

CREATE INDEX idx_system_email_messages_thread_created_at
ON system_email_messages(thread_id, created_at);

CREATE INDEX idx_system_email_messages_message_id_header
ON system_email_messages(message_id_header);

CREATE UNIQUE INDEX idx_system_email_messages_provider_message_id
ON system_email_messages(provider_message_id)
WHERE direction = 'outbound' AND provider_message_id IS NOT NULL;

CREATE INDEX idx_system_email_messages_quarantined_created_at
ON system_email_messages(created_at)
WHERE classification = 'quarantined';

CREATE INDEX idx_system_email_attachments_message_id
ON system_email_attachments(message_id);

CREATE INDEX idx_system_email_delivery_events_message_id
ON system_email_delivery_events(message_id);

CREATE INDEX idx_system_email_delivery_events_created_at
ON system_email_delivery_events(created_at);

CREATE UNIQUE INDEX idx_system_email_delivery_events_provider_event_id
ON system_email_delivery_events(provider_event_id)
WHERE provider_event_id IS NOT NULL;

CREATE INDEX idx_system_email_delivery_events_provider_event_created
ON system_email_delivery_events(provider, event_type, created_at);

CREATE INDEX idx_system_email_delivery_events_pending_effects
ON system_email_delivery_events(created_at)
WHERE provider = 'cloudflare-email-routing'
	AND event_type = 'received'
	AND needs_effect_reconcile = 1;

CREATE INDEX idx_system_email_delivery_events_recorded_usage_month
ON system_email_delivery_events(usage_month)
WHERE provider = 'cloudflare-email-routing'
	AND event_type = 'received'
	AND usage_effect_recorded_at IS NOT NULL;

CREATE INDEX idx_system_email_delivery_events_state_created
ON system_email_delivery_events(state, created_at, id)
WHERE provider = 'cloudflare-email-routing' AND state IS NOT NULL;

CREATE INDEX idx_system_email_delivery_events_dedupe_expires
ON system_email_delivery_events(dedupe_expires_at, id)
WHERE provider = 'cloudflare-email-routing-dedupe'
	AND dedupe_expires_at IS NOT NULL;

CREATE INDEX idx_email_outbound_provider_index_user_id
	ON email_outbound_provider_index(user_id);

CREATE UNIQUE INDEX idx_email_outbound_provider_index_message_id
	ON email_outbound_provider_index(message_id);

CREATE INDEX idx_email_outbound_provider_index_repair_owners_oldest
	ON email_outbound_provider_index_repair_owners(oldest_pending_at, user_id);

CREATE INDEX idx_email_delivery_alert_events_occurred_at
	ON email_delivery_alert_events(occurred_at, provider_event_id);

CREATE UNIQUE INDEX idx_user_repos_user_name ON user_repos(user_id, name);

CREATE UNIQUE INDEX idx_entity_source_artifacts_push_subscriptions_repo_id
	ON entity_source_artifacts_push_subscriptions(repo_id);

CREATE INDEX idx_email_inbound_due_owners_priority_due_at
	ON email_inbound_due_owners(due_at, user_id);

CREATE INDEX idx_users_username ON users(username);

CREATE INDEX idx_users_email ON users(email);

CREATE UNIQUE INDEX idx_users_stable_user_id
	ON users(stable_user_id);

CREATE UNIQUE INDEX idx_users_stripe_customer_id
	ON users(stripe_customer_id)
	WHERE stripe_customer_id IS NOT NULL;

CREATE INDEX idx_users_deleting_at
	ON users(deleting_at)
	WHERE deleting_at IS NOT NULL;

CREATE INDEX idx_user_integrations_user_app_slug
ON user_integrations(user_id, app_slug);

CREATE INDEX idx_user_integrations_platform_app
ON user_integrations(platform_app_slug)
WHERE platform_app_slug IS NOT NULL;

CREATE INDEX idx_saved_package_search_index_debt_user_id
ON saved_package_search_index_debt(user_id);

CREATE INDEX idx_username_redirects_user_id
ON username_redirects(user_id);

CREATE INDEX idx_package_kody_id_redirects_package_id
ON package_kody_id_redirects(package_id);

CREATE INDEX idx_repo_session_due_owners_due_at
	ON repo_session_due_owners(due_at, user_id);

CREATE INDEX idx_user_storage_buckets_user
ON user_storage_buckets(user_id);

CREATE INDEX idx_package_invocation_tokens_user_package
ON package_invocation_tokens(user_id, package_id);

CREATE UNIQUE INDEX idx_package_invocation_tokens_user_package_hash
ON package_invocation_tokens(user_id, package_id, token_hash);

CREATE UNIQUE INDEX idx_user_mcp_oauth_clients_client_id
	ON user_mcp_oauth_clients (client_id);

CREATE INDEX idx_user_mcp_oauth_clients_user_id
	ON user_mcp_oauth_clients (user_id);

CREATE INDEX idx_vector_embed_fingerprints_vector_id
ON vector_embed_fingerprints(vector_id);

CREATE INDEX idx_transactional_email_delivery_user_id
	ON transactional_email_delivery_index(user_id);

CREATE INDEX idx_secret_entries_bucket_id
ON secret_entries (bucket_id);

CREATE INDEX idx_secret_entries_name
ON secret_entries (name);

CREATE INDEX idx_secret_entries_lookup_hash
ON secret_entries (lookup_hash);

CREATE INDEX idx_platform_feedback_created_at_id
ON platform_feedback(created_at DESC, id DESC);

CREATE INDEX idx_platform_feedback_status_created_at_id
ON platform_feedback(status, created_at DESC, id DESC);

CREATE INDEX idx_platform_feedback_category_created_at_id
ON platform_feedback(category, created_at DESC, id DESC);

CREATE INDEX idx_platform_feedback_reviewer
ON platform_feedback(reviewed_by_user_id);

CREATE INDEX idx_platform_feedback_submitter_status
ON platform_feedback(submitter_user_id, status);

CREATE INDEX idx_platform_feedback_submitter_created_at
ON platform_feedback(submitter_user_id, created_at);

CREATE INDEX idx_platform_feedback_terminal_updated_at_id
ON platform_feedback(updated_at, id)
WHERE status IN ('resolved', 'dismissed');

CREATE INDEX idx_agent_package_conversation_uses_last_used
	ON agent_package_conversation_uses (last_used_at);

CREATE UNIQUE INDEX idx_community_listings_owner_package
	ON community_listings(owner_user_id, package_id);

CREATE INDEX idx_community_listings_status
	ON community_listings(status);

CREATE UNIQUE INDEX idx_community_listings_owner_kody_id_active
	ON community_listings(owner_user_id, kody_id) WHERE status = 'active';

CREATE INDEX idx_community_listings_category
	ON community_listings(category);

CREATE UNIQUE INDEX idx_user_email_claims_active_email
	ON user_email_claims(email)
	WHERE status = 'claimed';

CREATE INDEX idx_user_email_claims_user_id
	ON user_email_claims(user_id);

CREATE UNIQUE INDEX idx_pending_email_claim_releases_user_email
	ON pending_email_claim_releases(user_id, email);

CREATE UNIQUE INDEX idx_referrals_referee
	ON referrals(referee_stable_user_id);

CREATE INDEX idx_referrals_referrer
	ON referrals(referrer_stable_user_id);

CREATE UNIQUE INDEX idx_referrals_reward_invoice
	ON referrals(reward_invoice_id)
	WHERE reward_invoice_id IS NOT NULL;

CREATE INDEX idx_user_usage_campaigns_evaluated
	ON user_usage_campaigns(last_evaluated_at, user_id);

CREATE INDEX idx_user_usage_campaign_sends_user
	ON user_usage_campaign_sends(user_id);

CREATE UNIQUE INDEX user_usage_campaign_sends_advocate_unique
	ON user_usage_campaign_sends(user_id)
	WHERE template = 'advocate_referral_testimonial';

CREATE INDEX site_banners_enabled_priority_idx ON site_banners (enabled, priority DESC);

CREATE INDEX site_banner_dismissals_user_id_idx ON site_banner_dismissals (user_id);

CREATE INDEX idx_users_created_at
	ON users(created_at);

CREATE INDEX idx_users_last_active_at
	ON users(last_active_at)
	WHERE last_active_at IS NOT NULL;

CREATE INDEX idx_users_stripe_plan_price
	ON users(stripe_plan, stripe_price_id)
	WHERE stripe_plan IS NOT NULL;

CREATE INDEX idx_users_mcp_client_name
	ON users(mcp_client_name)
	WHERE first_mcp_connected_at IS NOT NULL;

CREATE INDEX idx_package_share_grants_package_id
ON package_share_grants(package_id);

CREATE INDEX idx_package_share_grants_owner_user_id
ON package_share_grants(owner_user_id);

CREATE INDEX idx_package_share_grants_grantee_user_id
ON package_share_grants(grantee_user_id);

CREATE INDEX idx_package_share_grants_invitee_email
ON package_share_grants(invitee_email);

CREATE UNIQUE INDEX idx_package_share_grants_active_email
ON package_share_grants(package_id, invitee_email)
WHERE status IN ('pending', 'accepted') AND invitee_email IS NOT NULL;

CREATE UNIQUE INDEX idx_package_share_grants_active_grantee
ON package_share_grants(package_id, grantee_user_id)
WHERE status IN ('pending', 'accepted') AND grantee_user_id IS NOT NULL;

CREATE UNIQUE INDEX idx_email_notification_destinations_user_email
	ON email_notification_destinations(user_id, email);

CREATE INDEX idx_email_notification_destinations_user_id
	ON email_notification_destinations(user_id);

CREATE UNIQUE INDEX idx_email_notification_destinations_user_default
	ON email_notification_destinations(user_id)
	WHERE is_default = 1;

CREATE INDEX idx_pending_email_destination_verifications_destination
	ON pending_email_destination_verifications(destination_id);

CREATE INDEX idx_secret_provider_bindings_package
	ON secret_provider_bindings(package_id);

CREATE INDEX idx_secret_provider_grants_user_package
	ON secret_provider_grants(user_id, package_id);

CREATE INDEX idx_webhook_apply_destination_pending_user
	ON webhook_apply_destination_pending(user_id, updated_at);

CREATE INDEX idx_webhook_apply_destination_grants_user
	ON webhook_apply_destination_grants(user_id, approved_at);

CREATE INDEX idx_durable_object_duration_daily_day
	ON durable_object_duration_daily (day);

CREATE UNIQUE INDEX idx_credit_ledger_entries_stripe_reference
	ON credit_ledger_entries (stripe_reference)
	WHERE stripe_reference IS NOT NULL;

CREATE INDEX idx_credit_ledger_entries_user_created
	ON credit_ledger_entries (user_id, created_at);

CREATE INDEX idx_jobs_user_next_run_at
	ON jobs(user_id, enabled, kill_switch_enabled, next_run_at);

CREATE INDEX idx_jobs_user_name
	ON jobs(user_id, name);

CREATE INDEX idx_jobs_source_id
	ON jobs(source_id);

CREATE INDEX idx_jobs_retention_candidates
	ON jobs(preserved, enabled, last_run_at, updated_at);

CREATE INDEX idx_jobs_user_enabled_expires_next_run
	ON jobs(user_id, enabled, kill_switch_enabled, expires_at, next_run_at);

CREATE INDEX idx_archived_job_artifacts_user_id
	ON archived_job_artifacts(user_id);

CREATE INDEX idx_archived_job_artifacts_retain_until
	ON archived_job_artifacts(retain_until);

INSERT INTO "roles" ("id", "name", "description", "created_at", "updated_at") VALUES (1, 'user', 'Default role for every account', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "roles" ("id", "name", "description", "created_at", "updated_at") VALUES (2, 'admin', 'Operator role', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE((SELECT max(id) FROM "roles"), 1), EXISTS (SELECT 1 FROM "roles"));

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (1, 'create', 'user', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (2, 'read', 'user', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (3, 'update', 'user', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (4, 'delete', 'user', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (5, 'create', 'role', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (6, 'read', 'role', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (7, 'update', 'role', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (8, 'delete', 'role', 'own', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (9, 'create', 'user', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (10, 'read', 'user', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (11, 'update', 'user', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (12, 'delete', 'user', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (13, 'create', 'role', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (14, 'read', 'role', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (15, 'update', 'role', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

INSERT INTO "permissions" ("id", "action", "entity", "access", "description", "created_at", "updated_at") VALUES (16, 'delete', 'role', 'any', '', '2026-08-04 20:55:22', '2026-08-04 20:55:22');

SELECT setval(pg_get_serial_sequence('permissions', 'id'), COALESCE((SELECT max(id) FROM "permissions"), 1), EXISTS (SELECT 1 FROM "permissions"));

SELECT setval(pg_get_serial_sequence('verifications', 'id'), COALESCE((SELECT max(id) FROM "verifications"), 1), EXISTS (SELECT 1 FROM "verifications"));

INSERT INTO "system_email_graph_authority" ("singleton", "authority", "cutover_at", "graph_mismatch_count", "provider_link_count") VALUES (1, 'dedicated', '2026-08-04 20:55:37', 0, 0);

INSERT INTO "email_user_graph_authority" ("singleton", "owner_count", "frozen_at", "dropped_at") VALUES (1, 0, '2026-08-04T20:55:38.184Z', '2026-08-04T20:55:39.233Z');

INSERT INTO "d1_storage_reconcile_cursor" ("singleton", "position", "updated_at") VALUES (1, '', '2026-08-04 20:55:39');

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT max(id) FROM "users"), 1), EXISTS (SELECT 1 FROM "users"));

INSERT INTO "repo_session_storage_bucket_cursor" ("singleton", "position", "updated_at") VALUES (1, '', '2026-09-30 14:28:44');

SELECT setval(pg_get_serial_sequence('referrals', 'id'), COALESCE((SELECT max(id) FROM "referrals"), 1), EXISTS (SELECT 1 FROM "referrals"));

SELECT setval(pg_get_serial_sequence('user_usage_campaign_sends', 'id'), COALESCE((SELECT max(id) FROM "user_usage_campaign_sends"), 1), EXISTS (SELECT 1 FROM "user_usage_campaign_sends"));

INSERT INTO "credit_debit_cursor" ("singleton", "position", "updated_at") VALUES (1, '', '2026-09-30 14:28:44');

SELECT setval(pg_get_serial_sequence('password_resets', 'id'), COALESCE((SELECT max(id) FROM "password_resets"), 1), EXISTS (SELECT 1 FROM "password_resets"));

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 5);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 1);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 8);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 4);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 6);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 2);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 7);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (1, 3);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 13);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 5);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 9);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 1);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 16);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 8);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 12);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 4);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 14);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 6);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 10);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 2);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 15);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 7);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 11);

INSERT INTO "role_permissions" ("role_id", "permission_id") VALUES (2, 3);

SELECT setval(pg_get_serial_sequence('email_verifications', 'id'), COALESCE((SELECT max(id) FROM "email_verifications"), 1), EXISTS (SELECT 1 FROM "email_verifications"));

SELECT setval(pg_get_serial_sequence('pending_email_changes', 'id'), COALESCE((SELECT max(id) FROM "pending_email_changes"), 1), EXISTS (SELECT 1 FROM "pending_email_changes"));

SELECT setval(pg_get_serial_sequence('oauth_connections', 'id'), COALESCE((SELECT max(id) FROM "oauth_connections"), 1), EXISTS (SELECT 1 FROM "oauth_connections"));

SELECT setval(pg_get_serial_sequence('user_email_claims', 'id'), COALESCE((SELECT max(id) FROM "user_email_claims"), 1), EXISTS (SELECT 1 FROM "user_email_claims"));

SELECT setval(pg_get_serial_sequence('pending_email_claim_releases', 'id'), COALESCE((SELECT max(id) FROM "pending_email_claim_releases"), 1), EXISTS (SELECT 1 FROM "pending_email_claim_releases"));

SELECT setval(pg_get_serial_sequence('pending_email_destination_verifications', 'id'), COALESCE((SELECT max(id) FROM "pending_email_destination_verifications"), 1), EXISTS (SELECT 1 FROM "pending_email_destination_verifications"));

CREATE FUNCTION delete_community_forks() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_TABLE_NAME = 'saved_packages' THEN
  DELETE FROM community_forks WHERE forker_user_id = OLD.user_id AND (forked_package_id = OLD.id OR forked_source_id = OLD.source_id);
 ELSE
  DELETE FROM community_forks WHERE forker_user_id = OLD.user_id AND forked_source_id = OLD.id;
 END IF;
 RETURN OLD;
END $$;
CREATE TRIGGER community_forks_delete_on_saved_package_delete AFTER DELETE ON saved_packages FOR EACH ROW EXECUTE FUNCTION delete_community_forks();
CREATE TRIGGER community_forks_delete_on_entity_source_delete AFTER DELETE ON entity_sources FOR EACH ROW EXECUTE FUNCTION delete_community_forks();
