-- Password reset and email verification links are opened before sign-in, and owner RLS
-- hides their token rows. Definers owned by NOLOGIN kody_token_resolver map a token hash
-- to its owner's stable id and nothing else; the flow then runs on that owner's scoped
-- writer. Knowing the hash means holding the token, so expiry stays an application check.
CREATE ROLE kody_token_resolver NOLOGIN;
GRANT USAGE ON SCHEMA public TO kody_token_resolver;
GRANT SELECT (id, stable_user_id) ON users TO kody_token_resolver;
CREATE POLICY users_token_resolver ON users FOR SELECT TO kody_token_resolver USING (true);
GRANT SELECT (user_id, token_hash) ON password_resets, email_verifications TO kody_token_resolver;
CREATE POLICY password_resets_token_resolver ON password_resets FOR SELECT TO kody_token_resolver USING (true);
CREATE POLICY email_verifications_token_resolver ON email_verifications FOR SELECT TO kody_token_resolver USING (true);

CREATE FUNCTION kody_password_reset_owner(lookup_token_hash text) RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
  SELECT u.stable_user_id FROM password_resets t JOIN users u ON u.id = t.user_id
  WHERE t.token_hash = lookup_token_hash
$fn$;
CREATE FUNCTION kody_email_verification_owner(lookup_token_hash text) RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
  SELECT u.stable_user_id FROM email_verifications t JOIN users u ON u.id = t.user_id
  WHERE t.token_hash = lookup_token_hash
$fn$;
ALTER FUNCTION kody_password_reset_owner(text) OWNER TO kody_token_resolver;
ALTER FUNCTION kody_email_verification_owner(text) OWNER TO kody_token_resolver;
REVOKE ALL ON FUNCTION kody_password_reset_owner(text), kody_email_verification_owner(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION kody_password_reset_owner(text), kody_email_verification_owner(text) TO kody_writer;

-- The rate-limit fallback (search, webhooks, destination verification) keys rows by user id
-- or IP, so no runtime role can read the table. Each call holds a per-key transaction
-- advisory lock: D1's single writer made count-then-insert atomic, PostgreSQL's READ
-- COMMITTED does not.
CREATE TABLE _rate_limits (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	key TEXT NOT NULL,
	ts BIGINT NOT NULL
);
CREATE INDEX idx_rate_limits_key_ts ON _rate_limits (key, ts);
CREATE ROLE kody_rate_limiter NOLOGIN;
GRANT USAGE ON SCHEMA public TO kody_rate_limiter;
GRANT SELECT, INSERT, DELETE ON _rate_limits TO kody_rate_limiter;

CREATE FUNCTION kody_rate_limit_take(lookup_key text, now_seconds bigint, window_seconds bigint, max_requests bigint)
RETURNS boolean
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(lookup_key, 0));
  DELETE FROM _rate_limits WHERE key = lookup_key AND ts <= now_seconds - window_seconds;
  IF (SELECT count(*) FROM _rate_limits WHERE key = lookup_key) >= max_requests THEN
    RETURN false;
  END IF;
  INSERT INTO _rate_limits (key, ts) VALUES (lookup_key, now_seconds);
  RETURN true;
END
$fn$;
-- Refund the newest slot for a key when the limited operation itself failed.
CREATE FUNCTION kody_rate_limit_release(lookup_key text) RETURNS void
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(lookup_key, 0));
  DELETE FROM _rate_limits WHERE id = (
    SELECT id FROM _rate_limits WHERE key = lookup_key ORDER BY id DESC LIMIT 1);
END
$fn$;
ALTER FUNCTION kody_rate_limit_take(text, bigint, bigint, bigint) OWNER TO kody_rate_limiter;
ALTER FUNCTION kody_rate_limit_release(text) OWNER TO kody_rate_limiter;
REVOKE ALL ON FUNCTION kody_rate_limit_take(text, bigint, bigint, bigint), kody_rate_limit_release(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION kody_rate_limit_take(text, bigint, bigint, bigint), kody_rate_limit_release(text) TO kody_writer;
